namespace ObjectARXLocatorWizard
{
    partial class ObjectARXLocatorForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.folderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.sdkpath = new System.Windows.Forms.TextBox();
            this.searchsdk = new System.Windows.Forms.Button();
            this.aboutbox = new System.Windows.Forms.Button();
            this.searchacad = new System.Windows.Forms.Button();
            this.acadpath = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.tabControlRefs = new System.Windows.Forms.TabControl();
            this.tpAutoCAD = new System.Windows.Forms.TabPage();
            this.accoremgd = new System.Windows.Forms.CheckBox();
            this.accui = new System.Windows.Forms.CheckBox();
            this.acdbmgdbrep = new System.Windows.Forms.CheckBox();
            this.interop1 = new System.Windows.Forms.CheckBox();
            this.interop0 = new System.Windows.Forms.CheckBox();
            this.acdx = new System.Windows.Forms.CheckBox();
            this.actcmgd = new System.Windows.Forms.CheckBox();
            this.acwindows = new System.Windows.Forms.CheckBox();
            this.adwindows = new System.Windows.Forms.CheckBox();
            this.acmgd = new System.Windows.Forms.CheckBox();
            this.acdbmgd = new System.Windows.Forms.CheckBox();
            this.tpMap3D = new System.Windows.Forms.TabPage();
            this.checkBox4 = new System.Windows.Forms.CheckBox();
            this.checkBox5 = new System.Windows.Forms.CheckBox();
            this.checkBox6 = new System.Windows.Forms.CheckBox();
            this.AcMPloygonMgd = new System.Windows.Forms.CheckBox();
            this.OsgeoFdoGeom = new System.Windows.Forms.CheckBox();
            this.OsgeoFdoCommon = new System.Windows.Forms.CheckBox();
            this.OsgeoFdo = new System.Windows.Forms.CheckBox();
            this.OsgeoMgPlatformBase = new System.Windows.Forms.CheckBox();
            this.OsgeoMgGeom = new System.Windows.Forms.CheckBox();
            this.OsgeoMgFoundation = new System.Windows.Forms.CheckBox();
            this.MgdMapApi = new System.Windows.Forms.CheckBox();
            this.mapPlatformCore = new System.Windows.Forms.CheckBox();
            this.mapPlatform = new System.Windows.Forms.CheckBox();
            this.tpCivil3D = new System.Windows.Forms.TabPage();
            this.checkBox7 = new System.Windows.Forms.CheckBox();
            this.checkBox8 = new System.Windows.Forms.CheckBox();
            this.checkBox10 = new System.Windows.Forms.CheckBox();
            this.aeccDbMgd = new System.Windows.Forms.CheckBox();
            this.dbxCommon = new System.Windows.Forms.CheckBox();
            this.aecBaseObjectLib = new System.Windows.Forms.CheckBox();
            this.aecBaseAppLip = new System.Windows.Forms.CheckBox();
            this.autocadTypeLib = new System.Windows.Forms.CheckBox();
            this.aeccSurvey = new System.Windows.Forms.CheckBox();
            this.aeccPipe = new System.Windows.Forms.CheckBox();
            this.aeccLand = new System.Windows.Forms.CheckBox();
            this.aeccRoadway = new System.Windows.Forms.CheckBox();
            this.aecBaseMgd = new System.Windows.Forms.CheckBox();
            this.tpACA = new System.Windows.Forms.TabPage();
            this.checkBox3 = new System.Windows.Forms.CheckBox();
            this.checkBox2 = new System.Windows.Forms.CheckBox();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.acaAecStructureMgd = new System.Windows.Forms.CheckBox();
            this.acaAecPropDataMgd = new System.Windows.Forms.CheckBox();
            this.acaAecRcpMgd = new System.Windows.Forms.CheckBox();
            this.acaAecUIBaseMgd = new System.Windows.Forms.CheckBox();
            this.acaAecUtilityMgd = new System.Windows.Forms.CheckBox();
            this.acaAecArchMgd = new System.Windows.Forms.CheckBox();
            this.acaArchDACHMgd = new System.Windows.Forms.CheckBox();
            this.acaAecBaseUtilsMgd = new System.Windows.Forms.CheckBox();
            this.acaAecProjectBaseMgd = new System.Windows.Forms.CheckBox();
            this.acaAecBaseMgd = new System.Windows.Forms.CheckBox();
            this.tpAME = new System.Windows.Forms.TabPage();
            this.checkBox9 = new System.Windows.Forms.CheckBox();
            this.checkBox11 = new System.Windows.Forms.CheckBox();
            this.checkBox12 = new System.Windows.Forms.CheckBox();
            this.ameAecStructureMgd = new System.Windows.Forms.CheckBox();
            this.ameAecPropDataMgd = new System.Windows.Forms.CheckBox();
            this.ameAecRcpMgd = new System.Windows.Forms.CheckBox();
            this.ameAecUIBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecUtilityMgd = new System.Windows.Forms.CheckBox();
            this.ameAecArchMgd = new System.Windows.Forms.CheckBox();
            this.ameAecArchDACHMgd = new System.Windows.Forms.CheckBox();
            this.ameAecBaseUtilsMgd = new System.Windows.Forms.CheckBox();
            this.ameAecProjectBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbBldSrvMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbElecBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbHvacBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbPartBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbPipeBaseMgd = new System.Windows.Forms.CheckBox();
            this.ameAecbPlumbingBaseMgd = new System.Windows.Forms.CheckBox();
            this.btnClearAll = new System.Windows.Forms.Button();
            this.btnSelectAll = new System.Windows.Forms.Button();
            this.lblRunAs = new System.Windows.Forms.Label();
            this.cbRunAs = new System.Windows.Forms.ComboBox();
            this.tabControlRefs.SuspendLayout();
            this.tpAutoCAD.SuspendLayout();
            this.tpMap3D.SuspendLayout();
            this.tpCivil3D.SuspendLayout();
            this.tpACA.SuspendLayout();
            this.tpAME.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.button1.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.button1.Enabled = false;
            this.button1.Location = new System.Drawing.Point(123, 503);
            this.button1.Margin = new System.Windows.Forms.Padding(4);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(100, 26);
            this.button1.TabIndex = 1;
            this.button1.Text = "Ok";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // button2
            // 
            this.button2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.button2.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.button2.Location = new System.Drawing.Point(229, 503);
            this.button2.Margin = new System.Windows.Forms.Padding(4);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(100, 26);
            this.button2.TabIndex = 2;
            this.button2.Text = "Cancel";
            this.button2.UseVisualStyleBackColor = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(16, 112);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(191, 15);
            this.label1.TabIndex = 7;
            this.label1.Text = "Assemblies to reference";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(16, 10);
            this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(647, 20);
            this.label2.TabIndex = 4;
            this.label2.Tag = "";
            this.label2.Text = "Specify the location of the folder inside the ObjectARX SDK that contains AcMgd.d" +
    "ll";
            this.label2.UseCompatibleTextRendering = true;
            // 
            // sdkpath
            // 
            this.sdkpath.Location = new System.Drawing.Point(20, 29);
            this.sdkpath.Margin = new System.Windows.Forms.Padding(4);
            this.sdkpath.Name = "sdkpath";
            this.sdkpath.Size = new System.Drawing.Size(489, 25);
            this.sdkpath.TabIndex = 5;
            this.sdkpath.TextChanged += new System.EventHandler(this.sdkpath_TextChanged);
            // 
            // searchsdk
            // 
            this.searchsdk.Location = new System.Drawing.Point(513, 25);
            this.searchsdk.Margin = new System.Windows.Forms.Padding(4);
            this.searchsdk.Name = "searchsdk";
            this.searchsdk.Size = new System.Drawing.Size(39, 26);
            this.searchsdk.TabIndex = 6;
            this.searchsdk.Text = "...";
            this.searchsdk.UseVisualStyleBackColor = true;
            this.searchsdk.Click += new System.EventHandler(this.searchsdk_Click);
            // 
            // aboutbox
            // 
            this.aboutbox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.aboutbox.Location = new System.Drawing.Point(339, 503);
            this.aboutbox.Margin = new System.Windows.Forms.Padding(4);
            this.aboutbox.Name = "aboutbox";
            this.aboutbox.Size = new System.Drawing.Size(100, 26);
            this.aboutbox.TabIndex = 3;
            this.aboutbox.Text = "About...";
            this.aboutbox.UseVisualStyleBackColor = true;
            this.aboutbox.Click += new System.EventHandler(this.aboutbox_Click);
            // 
            // searchacad
            // 
            this.searchacad.Location = new System.Drawing.Point(513, 73);
            this.searchacad.Margin = new System.Windows.Forms.Padding(4);
            this.searchacad.Name = "searchacad";
            this.searchacad.Size = new System.Drawing.Size(39, 26);
            this.searchacad.TabIndex = 20;
            this.searchacad.Text = "...";
            this.searchacad.UseVisualStyleBackColor = true;
            this.searchacad.Click += new System.EventHandler(this.searchacad_Click);
            // 
            // acadpath
            // 
            this.acadpath.Location = new System.Drawing.Point(19, 76);
            this.acadpath.Margin = new System.Windows.Forms.Padding(4);
            this.acadpath.Name = "acadpath";
            this.acadpath.Size = new System.Drawing.Size(489, 25);
            this.acadpath.TabIndex = 19;
            this.acadpath.TextChanged += new System.EventHandler(this.acadpath_TextChanged);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(15, 58);
            this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(307, 20);
            this.label3.TabIndex = 18;
            this.label3.Tag = "";
            this.label3.Text = "Specify the AutoCAD executable location";
            this.label3.UseCompatibleTextRendering = true;
            // 
            // tabControlRefs
            // 
            this.tabControlRefs.Controls.Add(this.tpAutoCAD);
            this.tabControlRefs.Controls.Add(this.tpMap3D);
            this.tabControlRefs.Controls.Add(this.tpCivil3D);
            this.tabControlRefs.Controls.Add(this.tpACA);
            this.tabControlRefs.Controls.Add(this.tpAME);
            this.tabControlRefs.Location = new System.Drawing.Point(19, 139);
            this.tabControlRefs.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tabControlRefs.Name = "tabControlRefs";
            this.tabControlRefs.SelectedIndex = 0;
            this.tabControlRefs.Size = new System.Drawing.Size(544, 308);
            this.tabControlRefs.TabIndex = 22;
            // 
            // tpAutoCAD
            // 
            this.tpAutoCAD.Controls.Add(this.accoremgd);
            this.tpAutoCAD.Controls.Add(this.accui);
            this.tpAutoCAD.Controls.Add(this.acdbmgdbrep);
            this.tpAutoCAD.Controls.Add(this.interop1);
            this.tpAutoCAD.Controls.Add(this.interop0);
            this.tpAutoCAD.Controls.Add(this.acdx);
            this.tpAutoCAD.Controls.Add(this.actcmgd);
            this.tpAutoCAD.Controls.Add(this.acwindows);
            this.tpAutoCAD.Controls.Add(this.adwindows);
            this.tpAutoCAD.Controls.Add(this.acmgd);
            this.tpAutoCAD.Controls.Add(this.acdbmgd);
            this.tpAutoCAD.Location = new System.Drawing.Point(4, 25);
            this.tpAutoCAD.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpAutoCAD.Name = "tpAutoCAD";
            this.tpAutoCAD.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpAutoCAD.Size = new System.Drawing.Size(536, 279);
            this.tpAutoCAD.TabIndex = 0;
            this.tpAutoCAD.Text = "AutoCAD";
            this.tpAutoCAD.UseVisualStyleBackColor = true;
            // 
            // accoremgd
            // 
            this.accoremgd.AutoSize = true;
            this.accoremgd.Checked = true;
            this.accoremgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.accoremgd.Enabled = false;
            this.accoremgd.Location = new System.Drawing.Point(113, 52);
            this.accoremgd.Margin = new System.Windows.Forms.Padding(4);
            this.accoremgd.Name = "accoremgd";
            this.accoremgd.Size = new System.Drawing.Size(125, 19);
            this.accoremgd.TabIndex = 32;
            this.accoremgd.Text = "AutoCAD Core";
            this.accoremgd.UseVisualStyleBackColor = true;
            // 
            // accui
            // 
            this.accui.AutoSize = true;
            this.accui.Location = new System.Drawing.Point(325, 131);
            this.accui.Margin = new System.Windows.Forms.Padding(4);
            this.accui.Name = "accui";
            this.accui.Size = new System.Drawing.Size(69, 19);
            this.accui.TabIndex = 31;
            this.accui.Text = "AcCui";
            this.accui.UseVisualStyleBackColor = true;
            // 
            // acdbmgdbrep
            // 
            this.acdbmgdbrep.AutoSize = true;
            this.acdbmgdbrep.Location = new System.Drawing.Point(325, 104);
            this.acdbmgdbrep.Margin = new System.Windows.Forms.Padding(4);
            this.acdbmgdbrep.Name = "acdbmgdbrep";
            this.acdbmgdbrep.Size = new System.Drawing.Size(69, 19);
            this.acdbmgdbrep.TabIndex = 30;
            this.acdbmgdbrep.Text = "B-Rep";
            this.acdbmgdbrep.UseVisualStyleBackColor = true;
            // 
            // interop1
            // 
            this.interop1.AutoSize = true;
            this.interop1.Location = new System.Drawing.Point(325, 77);
            this.interop1.Margin = new System.Windows.Forms.Padding(4);
            this.interop1.Name = "interop1";
            this.interop1.Size = new System.Drawing.Size(149, 19);
            this.interop1.TabIndex = 29;
            this.interop1.Text = "AutoCAD Interop";
            this.interop1.UseVisualStyleBackColor = true;
            // 
            // interop0
            // 
            this.interop0.AutoSize = true;
            this.interop0.Location = new System.Drawing.Point(325, 52);
            this.interop0.Margin = new System.Windows.Forms.Padding(4);
            this.interop0.Name = "interop0";
            this.interop0.Size = new System.Drawing.Size(205, 19);
            this.interop0.TabIndex = 28;
            this.interop0.Text = "AutoCAD Interop Common";
            this.interop0.UseVisualStyleBackColor = true;
            // 
            // acdx
            // 
            this.acdx.AutoSize = true;
            this.acdx.Location = new System.Drawing.Point(325, 24);
            this.acdx.Margin = new System.Windows.Forms.Padding(4);
            this.acdx.Name = "acdx";
            this.acdx.Size = new System.Drawing.Size(61, 19);
            this.acdx.TabIndex = 27;
            this.acdx.Text = "AcDx";
            this.acdx.UseVisualStyleBackColor = true;
            // 
            // actcmgd
            // 
            this.actcmgd.AutoSize = true;
            this.actcmgd.Location = new System.Drawing.Point(17, 131);
            this.actcmgd.Margin = new System.Windows.Forms.Padding(4);
            this.actcmgd.Name = "actcmgd";
            this.actcmgd.Size = new System.Drawing.Size(61, 19);
            this.actcmgd.TabIndex = 26;
            this.actcmgd.Text = "AcTc";
            this.actcmgd.UseVisualStyleBackColor = true;
            // 
            // acwindows
            // 
            this.acwindows.AutoSize = true;
            this.acwindows.Location = new System.Drawing.Point(17, 104);
            this.acwindows.Margin = new System.Windows.Forms.Padding(4);
            this.acwindows.Name = "acwindows";
            this.acwindows.Size = new System.Drawing.Size(101, 19);
            this.acwindows.TabIndex = 25;
            this.acwindows.Text = "AcWindows";
            this.acwindows.UseVisualStyleBackColor = true;
            // 
            // adwindows
            // 
            this.adwindows.AutoSize = true;
            this.adwindows.Location = new System.Drawing.Point(17, 77);
            this.adwindows.Margin = new System.Windows.Forms.Padding(4);
            this.adwindows.Name = "adwindows";
            this.adwindows.Size = new System.Drawing.Size(101, 19);
            this.adwindows.TabIndex = 24;
            this.adwindows.Text = "AdWindows";
            this.adwindows.UseVisualStyleBackColor = true;
            // 
            // acmgd
            // 
            this.acmgd.AutoSize = true;
            this.acmgd.Checked = true;
            this.acmgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acmgd.Enabled = false;
            this.acmgd.Location = new System.Drawing.Point(17, 52);
            this.acmgd.Margin = new System.Windows.Forms.Padding(4);
            this.acmgd.Name = "acmgd";
            this.acmgd.Size = new System.Drawing.Size(85, 19);
            this.acmgd.TabIndex = 23;
            this.acmgd.Text = "AutoCAD";
            this.acmgd.UseVisualStyleBackColor = true;
            // 
            // acdbmgd
            // 
            this.acdbmgd.AutoSize = true;
            this.acdbmgd.Checked = true;
            this.acdbmgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acdbmgd.Enabled = false;
            this.acdbmgd.Location = new System.Drawing.Point(17, 24);
            this.acdbmgd.Margin = new System.Windows.Forms.Padding(4);
            this.acdbmgd.Name = "acdbmgd";
            this.acdbmgd.Size = new System.Drawing.Size(157, 19);
            this.acdbmgd.TabIndex = 22;
            this.acdbmgd.Text = "AutoCAD Database";
            this.acdbmgd.UseVisualStyleBackColor = true;
            // 
            // tpMap3D
            // 
            this.tpMap3D.Controls.Add(this.checkBox4);
            this.tpMap3D.Controls.Add(this.checkBox5);
            this.tpMap3D.Controls.Add(this.checkBox6);
            this.tpMap3D.Controls.Add(this.AcMPloygonMgd);
            this.tpMap3D.Controls.Add(this.OsgeoFdoGeom);
            this.tpMap3D.Controls.Add(this.OsgeoFdoCommon);
            this.tpMap3D.Controls.Add(this.OsgeoFdo);
            this.tpMap3D.Controls.Add(this.OsgeoMgPlatformBase);
            this.tpMap3D.Controls.Add(this.OsgeoMgGeom);
            this.tpMap3D.Controls.Add(this.OsgeoMgFoundation);
            this.tpMap3D.Controls.Add(this.MgdMapApi);
            this.tpMap3D.Controls.Add(this.mapPlatformCore);
            this.tpMap3D.Controls.Add(this.mapPlatform);
            this.tpMap3D.Location = new System.Drawing.Point(4, 25);
            this.tpMap3D.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpMap3D.Name = "tpMap3D";
            this.tpMap3D.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpMap3D.Size = new System.Drawing.Size(536, 279);
            this.tpMap3D.TabIndex = 1;
            this.tpMap3D.Text = "Map 3D";
            this.tpMap3D.UseVisualStyleBackColor = true;
            this.tpMap3D.UseWaitCursor = true;
            // 
            // checkBox4
            // 
            this.checkBox4.AutoSize = true;
            this.checkBox4.Checked = true;
            this.checkBox4.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox4.Enabled = false;
            this.checkBox4.Location = new System.Drawing.Point(325, 17);
            this.checkBox4.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox4.Name = "checkBox4";
            this.checkBox4.Size = new System.Drawing.Size(101, 19);
            this.checkBox4.TabIndex = 31;
            this.checkBox4.Text = "AcCoreMgd";
            this.checkBox4.UseVisualStyleBackColor = true;
            this.checkBox4.UseWaitCursor = true;
            // 
            // checkBox5
            // 
            this.checkBox5.AutoSize = true;
            this.checkBox5.Checked = true;
            this.checkBox5.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox5.Enabled = false;
            this.checkBox5.Location = new System.Drawing.Point(187, 17);
            this.checkBox5.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox5.Name = "checkBox5";
            this.checkBox5.Size = new System.Drawing.Size(69, 19);
            this.checkBox5.TabIndex = 30;
            this.checkBox5.Text = "AcMgd";
            this.checkBox5.UseVisualStyleBackColor = true;
            this.checkBox5.UseWaitCursor = true;
            // 
            // checkBox6
            // 
            this.checkBox6.AutoSize = true;
            this.checkBox6.Checked = true;
            this.checkBox6.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox6.Enabled = false;
            this.checkBox6.Location = new System.Drawing.Point(19, 17);
            this.checkBox6.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox6.Name = "checkBox6";
            this.checkBox6.Size = new System.Drawing.Size(85, 19);
            this.checkBox6.TabIndex = 29;
            this.checkBox6.Text = "AcDbMgd";
            this.checkBox6.UseVisualStyleBackColor = true;
            this.checkBox6.UseWaitCursor = true;
            // 
            // AcMPloygonMgd
            // 
            this.AcMPloygonMgd.AutoSize = true;
            this.AcMPloygonMgd.Location = new System.Drawing.Point(325, 154);
            this.AcMPloygonMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.AcMPloygonMgd.Name = "AcMPloygonMgd";
            this.AcMPloygonMgd.Size = new System.Drawing.Size(133, 19);
            this.AcMPloygonMgd.TabIndex = 9;
            this.AcMPloygonMgd.Text = "AcMPolygonMGD";
            this.AcMPloygonMgd.UseVisualStyleBackColor = true;
            this.AcMPloygonMgd.UseWaitCursor = true;
            // 
            // OsgeoFdoGeom
            // 
            this.OsgeoFdoGeom.AutoSize = true;
            this.OsgeoFdoGeom.Location = new System.Drawing.Point(325, 128);
            this.OsgeoFdoGeom.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoFdoGeom.Name = "OsgeoFdoGeom";
            this.OsgeoFdoGeom.Size = new System.Drawing.Size(173, 19);
            this.OsgeoFdoGeom.TabIndex = 8;
            this.OsgeoFdoGeom.Text = "OSGeo.FDO.Geometry";
            this.OsgeoFdoGeom.UseVisualStyleBackColor = true;
            this.OsgeoFdoGeom.UseWaitCursor = true;
            // 
            // OsgeoFdoCommon
            // 
            this.OsgeoFdoCommon.AutoSize = true;
            this.OsgeoFdoCommon.Location = new System.Drawing.Point(325, 103);
            this.OsgeoFdoCommon.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoFdoCommon.Name = "OsgeoFdoCommon";
            this.OsgeoFdoCommon.Size = new System.Drawing.Size(157, 19);
            this.OsgeoFdoCommon.TabIndex = 7;
            this.OsgeoFdoCommon.Text = "OSGeo.FDO.Common";
            this.OsgeoFdoCommon.UseVisualStyleBackColor = true;
            this.OsgeoFdoCommon.UseWaitCursor = true;
            // 
            // OsgeoFdo
            // 
            this.OsgeoFdo.AutoSize = true;
            this.OsgeoFdo.Location = new System.Drawing.Point(325, 77);
            this.OsgeoFdo.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoFdo.Name = "OsgeoFdo";
            this.OsgeoFdo.Size = new System.Drawing.Size(101, 19);
            this.OsgeoFdo.TabIndex = 6;
            this.OsgeoFdo.Text = "OSGeo.FDO";
            this.OsgeoFdo.UseVisualStyleBackColor = true;
            this.OsgeoFdo.UseWaitCursor = true;
            // 
            // OsgeoMgPlatformBase
            // 
            this.OsgeoMgPlatformBase.AutoSize = true;
            this.OsgeoMgPlatformBase.Checked = true;
            this.OsgeoMgPlatformBase.CheckState = System.Windows.Forms.CheckState.Checked;
            this.OsgeoMgPlatformBase.Location = new System.Drawing.Point(17, 154);
            this.OsgeoMgPlatformBase.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoMgPlatformBase.Name = "OsgeoMgPlatformBase";
            this.OsgeoMgPlatformBase.Size = new System.Drawing.Size(245, 19);
            this.OsgeoMgPlatformBase.TabIndex = 5;
            this.OsgeoMgPlatformBase.Text = "OSGeo.MapGuide.PlatformBase";
            this.OsgeoMgPlatformBase.UseVisualStyleBackColor = true;
            this.OsgeoMgPlatformBase.UseWaitCursor = true;
            // 
            // OsgeoMgGeom
            // 
            this.OsgeoMgGeom.AutoSize = true;
            this.OsgeoMgGeom.Checked = true;
            this.OsgeoMgGeom.CheckState = System.Windows.Forms.CheckState.Checked;
            this.OsgeoMgGeom.Location = new System.Drawing.Point(17, 128);
            this.OsgeoMgGeom.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoMgGeom.Name = "OsgeoMgGeom";
            this.OsgeoMgGeom.Size = new System.Drawing.Size(213, 19);
            this.OsgeoMgGeom.TabIndex = 4;
            this.OsgeoMgGeom.Text = "OSGeo.MapGuide.Geometry";
            this.OsgeoMgGeom.UseVisualStyleBackColor = true;
            this.OsgeoMgGeom.UseWaitCursor = true;
            // 
            // OsgeoMgFoundation
            // 
            this.OsgeoMgFoundation.AutoSize = true;
            this.OsgeoMgFoundation.Checked = true;
            this.OsgeoMgFoundation.CheckState = System.Windows.Forms.CheckState.Checked;
            this.OsgeoMgFoundation.Location = new System.Drawing.Point(17, 103);
            this.OsgeoMgFoundation.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.OsgeoMgFoundation.Name = "OsgeoMgFoundation";
            this.OsgeoMgFoundation.Size = new System.Drawing.Size(229, 19);
            this.OsgeoMgFoundation.TabIndex = 3;
            this.OsgeoMgFoundation.Text = "OSGeo.MapGuide.Foundation";
            this.OsgeoMgFoundation.UseVisualStyleBackColor = true;
            this.OsgeoMgFoundation.UseWaitCursor = true;
            // 
            // MgdMapApi
            // 
            this.MgdMapApi.AutoSize = true;
            this.MgdMapApi.Location = new System.Drawing.Point(325, 53);
            this.MgdMapApi.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MgdMapApi.Name = "MgdMapApi";
            this.MgdMapApi.Size = new System.Drawing.Size(133, 19);
            this.MgdMapApi.TabIndex = 2;
            this.MgdMapApi.Text = "ManagedMapApi";
            this.MgdMapApi.UseVisualStyleBackColor = true;
            this.MgdMapApi.UseWaitCursor = true;
            // 
            // mapPlatformCore
            // 
            this.mapPlatformCore.AutoSize = true;
            this.mapPlatformCore.Location = new System.Drawing.Point(17, 77);
            this.mapPlatformCore.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.mapPlatformCore.Name = "mapPlatformCore";
            this.mapPlatformCore.Size = new System.Drawing.Size(317, 19);
            this.mapPlatformCore.TabIndex = 1;
            this.mapPlatformCore.Text = "Autodesk.Map.Platform.Core(for 2012)";
            this.mapPlatformCore.UseVisualStyleBackColor = true;
            this.mapPlatformCore.UseWaitCursor = true;
            // 
            // mapPlatform
            // 
            this.mapPlatform.AutoSize = true;
            this.mapPlatform.Checked = true;
            this.mapPlatform.CheckState = System.Windows.Forms.CheckState.Checked;
            this.mapPlatform.Location = new System.Drawing.Point(17, 53);
            this.mapPlatform.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.mapPlatform.Name = "mapPlatform";
            this.mapPlatform.Size = new System.Drawing.Size(197, 19);
            this.mapPlatform.TabIndex = 0;
            this.mapPlatform.Text = "Autodesk.Map.Platform";
            this.mapPlatform.UseVisualStyleBackColor = true;
            this.mapPlatform.UseWaitCursor = true;
            // 
            // tpCivil3D
            // 
            this.tpCivil3D.Controls.Add(this.checkBox7);
            this.tpCivil3D.Controls.Add(this.checkBox8);
            this.tpCivil3D.Controls.Add(this.checkBox10);
            this.tpCivil3D.Controls.Add(this.aeccDbMgd);
            this.tpCivil3D.Controls.Add(this.dbxCommon);
            this.tpCivil3D.Controls.Add(this.aecBaseObjectLib);
            this.tpCivil3D.Controls.Add(this.aecBaseAppLip);
            this.tpCivil3D.Controls.Add(this.autocadTypeLib);
            this.tpCivil3D.Controls.Add(this.aeccSurvey);
            this.tpCivil3D.Controls.Add(this.aeccPipe);
            this.tpCivil3D.Controls.Add(this.aeccLand);
            this.tpCivil3D.Controls.Add(this.aeccRoadway);
            this.tpCivil3D.Controls.Add(this.aecBaseMgd);
            this.tpCivil3D.Location = new System.Drawing.Point(4, 25);
            this.tpCivil3D.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpCivil3D.Name = "tpCivil3D";
            this.tpCivil3D.Size = new System.Drawing.Size(536, 279);
            this.tpCivil3D.TabIndex = 2;
            this.tpCivil3D.Text = "Civil 3D";
            this.tpCivil3D.UseVisualStyleBackColor = true;
            // 
            // checkBox7
            // 
            this.checkBox7.AutoSize = true;
            this.checkBox7.Checked = true;
            this.checkBox7.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox7.Enabled = false;
            this.checkBox7.Location = new System.Drawing.Point(235, 9);
            this.checkBox7.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox7.Name = "checkBox7";
            this.checkBox7.Size = new System.Drawing.Size(101, 19);
            this.checkBox7.TabIndex = 31;
            this.checkBox7.Text = "AcCoreMgd";
            this.checkBox7.UseVisualStyleBackColor = true;
            // 
            // checkBox8
            // 
            this.checkBox8.AutoSize = true;
            this.checkBox8.Checked = true;
            this.checkBox8.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox8.Enabled = false;
            this.checkBox8.Location = new System.Drawing.Point(133, 9);
            this.checkBox8.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox8.Name = "checkBox8";
            this.checkBox8.Size = new System.Drawing.Size(69, 19);
            this.checkBox8.TabIndex = 30;
            this.checkBox8.Text = "AcMgd";
            this.checkBox8.UseVisualStyleBackColor = true;
            // 
            // checkBox10
            // 
            this.checkBox10.AutoSize = true;
            this.checkBox10.Checked = true;
            this.checkBox10.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox10.Enabled = false;
            this.checkBox10.Location = new System.Drawing.Point(16, 9);
            this.checkBox10.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox10.Name = "checkBox10";
            this.checkBox10.Size = new System.Drawing.Size(85, 19);
            this.checkBox10.TabIndex = 29;
            this.checkBox10.Text = "AcDbMgd";
            this.checkBox10.UseVisualStyleBackColor = true;
            // 
            // aeccDbMgd
            // 
            this.aeccDbMgd.AutoSize = true;
            this.aeccDbMgd.Checked = true;
            this.aeccDbMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.aeccDbMgd.Location = new System.Drawing.Point(235, 49);
            this.aeccDbMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aeccDbMgd.Name = "aeccDbMgd";
            this.aeccDbMgd.Size = new System.Drawing.Size(101, 19);
            this.aeccDbMgd.TabIndex = 15;
            this.aeccDbMgd.Text = "AeccDbMgd";
            this.aeccDbMgd.UseVisualStyleBackColor = true;
            // 
            // dbxCommon
            // 
            this.dbxCommon.AutoSize = true;
            this.dbxCommon.Location = new System.Drawing.Point(15, 173);
            this.dbxCommon.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dbxCommon.Name = "dbxCommon";
            this.dbxCommon.Size = new System.Drawing.Size(325, 19);
            this.dbxCommon.TabIndex = 14;
            this.dbxCommon.Text = "AutoCAD/ObjectDBX Common Type Library";
            this.dbxCommon.UseVisualStyleBackColor = true;
            // 
            // aecBaseObjectLib
            // 
            this.aecBaseObjectLib.AutoSize = true;
            this.aecBaseObjectLib.Location = new System.Drawing.Point(15, 246);
            this.aecBaseObjectLib.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aecBaseObjectLib.Name = "aecBaseObjectLib";
            this.aecBaseObjectLib.Size = new System.Drawing.Size(213, 19);
            this.aecBaseObjectLib.TabIndex = 8;
            this.aecBaseObjectLib.Text = "AEC Base Object Library";
            this.aecBaseObjectLib.UseVisualStyleBackColor = true;
            // 
            // aecBaseAppLip
            // 
            this.aecBaseAppLip.AutoSize = true;
            this.aecBaseAppLip.Location = new System.Drawing.Point(15, 221);
            this.aecBaseAppLip.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aecBaseAppLip.Name = "aecBaseAppLip";
            this.aecBaseAppLip.Size = new System.Drawing.Size(253, 19);
            this.aecBaseAppLip.TabIndex = 7;
            this.aecBaseAppLip.Text = "AEC Base Application Library";
            this.aecBaseAppLip.UseVisualStyleBackColor = true;
            // 
            // autocadTypeLib
            // 
            this.autocadTypeLib.AutoSize = true;
            this.autocadTypeLib.Location = new System.Drawing.Point(15, 197);
            this.autocadTypeLib.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.autocadTypeLib.Name = "autocadTypeLib";
            this.autocadTypeLib.Size = new System.Drawing.Size(189, 19);
            this.autocadTypeLib.TabIndex = 6;
            this.autocadTypeLib.Text = "AutoCAD Type Library";
            this.autocadTypeLib.UseVisualStyleBackColor = true;
            // 
            // aeccSurvey
            // 
            this.aeccSurvey.AutoSize = true;
            this.aeccSurvey.Location = new System.Drawing.Point(15, 148);
            this.aeccSurvey.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aeccSurvey.Name = "aeccSurvey";
            this.aeccSurvey.Size = new System.Drawing.Size(285, 19);
            this.aeccSurvey.TabIndex = 5;
            this.aeccSurvey.Text = "Autodesk.AECC.Interop.(UI)Survey";
            this.aeccSurvey.UseVisualStyleBackColor = true;
            this.aeccSurvey.CheckedChanged += new System.EventHandler(this.aeccSurvey_CheckedChanged);
            // 
            // aeccPipe
            // 
            this.aeccPipe.AutoSize = true;
            this.aeccPipe.Location = new System.Drawing.Point(15, 122);
            this.aeccPipe.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aeccPipe.Name = "aeccPipe";
            this.aeccPipe.Size = new System.Drawing.Size(269, 19);
            this.aeccPipe.TabIndex = 4;
            this.aeccPipe.Text = "Autodesk.AECC.Interop.(UI)Pipe";
            this.aeccPipe.UseVisualStyleBackColor = true;
            this.aeccPipe.CheckedChanged += new System.EventHandler(this.aeccPipe_CheckedChanged);
            // 
            // aeccLand
            // 
            this.aeccLand.AutoSize = true;
            this.aeccLand.Location = new System.Drawing.Point(15, 74);
            this.aeccLand.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aeccLand.Name = "aeccLand";
            this.aeccLand.Size = new System.Drawing.Size(269, 19);
            this.aeccLand.TabIndex = 3;
            this.aeccLand.Text = "Autodesk.AECC.Interop.(UI)Land";
            this.aeccLand.UseVisualStyleBackColor = true;
            this.aeccLand.CheckedChanged += new System.EventHandler(this.aeccLand_CheckedChanged);
            // 
            // aeccRoadway
            // 
            this.aeccRoadway.AutoSize = true;
            this.aeccRoadway.Location = new System.Drawing.Point(15, 97);
            this.aeccRoadway.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aeccRoadway.Name = "aeccRoadway";
            this.aeccRoadway.Size = new System.Drawing.Size(293, 19);
            this.aeccRoadway.TabIndex = 2;
            this.aeccRoadway.Text = "Autodesk.AECC.Interop.(UI)Roadway";
            this.aeccRoadway.UseVisualStyleBackColor = true;
            this.aeccRoadway.CheckedChanged += new System.EventHandler(this.aeccRoadway_CheckedChanged);
            // 
            // aecBaseMgd
            // 
            this.aecBaseMgd.AutoSize = true;
            this.aecBaseMgd.Checked = true;
            this.aecBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.aecBaseMgd.Location = new System.Drawing.Point(16, 49);
            this.aecBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.aecBaseMgd.Name = "aecBaseMgd";
            this.aecBaseMgd.Size = new System.Drawing.Size(109, 19);
            this.aecBaseMgd.TabIndex = 1;
            this.aecBaseMgd.Text = "AecBaseMgd";
            this.aecBaseMgd.UseVisualStyleBackColor = true;
            // 
            // tpACA
            // 
            this.tpACA.Controls.Add(this.checkBox3);
            this.tpACA.Controls.Add(this.checkBox2);
            this.tpACA.Controls.Add(this.checkBox1);
            this.tpACA.Controls.Add(this.acaAecStructureMgd);
            this.tpACA.Controls.Add(this.acaAecPropDataMgd);
            this.tpACA.Controls.Add(this.acaAecRcpMgd);
            this.tpACA.Controls.Add(this.acaAecUIBaseMgd);
            this.tpACA.Controls.Add(this.acaAecUtilityMgd);
            this.tpACA.Controls.Add(this.acaAecArchMgd);
            this.tpACA.Controls.Add(this.acaArchDACHMgd);
            this.tpACA.Controls.Add(this.acaAecBaseUtilsMgd);
            this.tpACA.Controls.Add(this.acaAecProjectBaseMgd);
            this.tpACA.Controls.Add(this.acaAecBaseMgd);
            this.tpACA.Location = new System.Drawing.Point(4, 25);
            this.tpACA.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpACA.Name = "tpACA";
            this.tpACA.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpACA.Size = new System.Drawing.Size(536, 279);
            this.tpACA.TabIndex = 3;
            this.tpACA.Text = "ACA";
            this.tpACA.UseVisualStyleBackColor = true;
            // 
            // checkBox3
            // 
            this.checkBox3.AutoSize = true;
            this.checkBox3.Checked = true;
            this.checkBox3.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox3.Enabled = false;
            this.checkBox3.Location = new System.Drawing.Point(245, 22);
            this.checkBox3.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox3.Name = "checkBox3";
            this.checkBox3.Size = new System.Drawing.Size(101, 19);
            this.checkBox3.TabIndex = 28;
            this.checkBox3.Text = "AcCoreMgd";
            this.checkBox3.UseVisualStyleBackColor = true;
            // 
            // checkBox2
            // 
            this.checkBox2.AutoSize = true;
            this.checkBox2.Checked = true;
            this.checkBox2.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox2.Enabled = false;
            this.checkBox2.Location = new System.Drawing.Point(145, 22);
            this.checkBox2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox2.Name = "checkBox2";
            this.checkBox2.Size = new System.Drawing.Size(69, 19);
            this.checkBox2.TabIndex = 27;
            this.checkBox2.Text = "AcMgd";
            this.checkBox2.UseVisualStyleBackColor = true;
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.Checked = true;
            this.checkBox1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox1.Enabled = false;
            this.checkBox1.Location = new System.Drawing.Point(27, 22);
            this.checkBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(85, 19);
            this.checkBox1.TabIndex = 26;
            this.checkBox1.Text = "AcDbMgd";
            this.checkBox1.UseVisualStyleBackColor = true;
            // 
            // acaAecStructureMgd
            // 
            this.acaAecStructureMgd.AutoSize = true;
            this.acaAecStructureMgd.Checked = true;
            this.acaAecStructureMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecStructureMgd.Location = new System.Drawing.Point(245, 107);
            this.acaAecStructureMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecStructureMgd.Name = "acaAecStructureMgd";
            this.acaAecStructureMgd.Size = new System.Drawing.Size(149, 19);
            this.acaAecStructureMgd.TabIndex = 25;
            this.acaAecStructureMgd.Text = "AecStructureMgd";
            this.acaAecStructureMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecPropDataMgd
            // 
            this.acaAecPropDataMgd.AutoSize = true;
            this.acaAecPropDataMgd.Checked = true;
            this.acaAecPropDataMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecPropDataMgd.Location = new System.Drawing.Point(245, 56);
            this.acaAecPropDataMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecPropDataMgd.Name = "acaAecPropDataMgd";
            this.acaAecPropDataMgd.Size = new System.Drawing.Size(141, 19);
            this.acaAecPropDataMgd.TabIndex = 24;
            this.acaAecPropDataMgd.Text = "AecPropDataMgd";
            this.acaAecPropDataMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecRcpMgd
            // 
            this.acaAecRcpMgd.AutoSize = true;
            this.acaAecRcpMgd.Checked = true;
            this.acaAecRcpMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecRcpMgd.Location = new System.Drawing.Point(245, 82);
            this.acaAecRcpMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecRcpMgd.Name = "acaAecRcpMgd";
            this.acaAecRcpMgd.Size = new System.Drawing.Size(101, 19);
            this.acaAecRcpMgd.TabIndex = 23;
            this.acaAecRcpMgd.Text = "AecRcpMgd";
            this.acaAecRcpMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecUIBaseMgd
            // 
            this.acaAecUIBaseMgd.AutoSize = true;
            this.acaAecUIBaseMgd.Checked = true;
            this.acaAecUIBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecUIBaseMgd.Location = new System.Drawing.Point(245, 133);
            this.acaAecUIBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecUIBaseMgd.Name = "acaAecUIBaseMgd";
            this.acaAecUIBaseMgd.Size = new System.Drawing.Size(125, 19);
            this.acaAecUIBaseMgd.TabIndex = 20;
            this.acaAecUIBaseMgd.Text = "AecUIBaseMgd";
            this.acaAecUIBaseMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecUtilityMgd
            // 
            this.acaAecUtilityMgd.AutoSize = true;
            this.acaAecUtilityMgd.Checked = true;
            this.acaAecUtilityMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecUtilityMgd.Location = new System.Drawing.Point(245, 157);
            this.acaAecUtilityMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecUtilityMgd.Name = "acaAecUtilityMgd";
            this.acaAecUtilityMgd.Size = new System.Drawing.Size(133, 19);
            this.acaAecUtilityMgd.TabIndex = 19;
            this.acaAecUtilityMgd.Text = "AecUtilityMgd";
            this.acaAecUtilityMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecArchMgd
            // 
            this.acaAecArchMgd.AutoSize = true;
            this.acaAecArchMgd.Checked = true;
            this.acaAecArchMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecArchMgd.Location = new System.Drawing.Point(27, 56);
            this.acaAecArchMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecArchMgd.Name = "acaAecArchMgd";
            this.acaAecArchMgd.Size = new System.Drawing.Size(109, 19);
            this.acaAecArchMgd.TabIndex = 13;
            this.acaAecArchMgd.Text = "AecArchMgd";
            this.acaAecArchMgd.UseVisualStyleBackColor = true;
            // 
            // acaArchDACHMgd
            // 
            this.acaArchDACHMgd.AutoSize = true;
            this.acaArchDACHMgd.Checked = true;
            this.acaArchDACHMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaArchDACHMgd.Location = new System.Drawing.Point(27, 82);
            this.acaArchDACHMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaArchDACHMgd.Name = "acaArchDACHMgd";
            this.acaArchDACHMgd.Size = new System.Drawing.Size(141, 19);
            this.acaArchDACHMgd.TabIndex = 12;
            this.acaArchDACHMgd.Text = "AecArchDACHMgd";
            this.acaArchDACHMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecBaseUtilsMgd
            // 
            this.acaAecBaseUtilsMgd.AutoSize = true;
            this.acaAecBaseUtilsMgd.Checked = true;
            this.acaAecBaseUtilsMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecBaseUtilsMgd.Location = new System.Drawing.Point(27, 133);
            this.acaAecBaseUtilsMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecBaseUtilsMgd.Name = "acaAecBaseUtilsMgd";
            this.acaAecBaseUtilsMgd.Size = new System.Drawing.Size(149, 19);
            this.acaAecBaseUtilsMgd.TabIndex = 10;
            this.acaAecBaseUtilsMgd.Text = "AecBaseUtilsMgd";
            this.acaAecBaseUtilsMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecProjectBaseMgd
            // 
            this.acaAecProjectBaseMgd.AutoSize = true;
            this.acaAecProjectBaseMgd.Checked = true;
            this.acaAecProjectBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecProjectBaseMgd.Location = new System.Drawing.Point(27, 157);
            this.acaAecProjectBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecProjectBaseMgd.Name = "acaAecProjectBaseMgd";
            this.acaAecProjectBaseMgd.Size = new System.Drawing.Size(165, 19);
            this.acaAecProjectBaseMgd.TabIndex = 4;
            this.acaAecProjectBaseMgd.Text = "AecProjectBaseMgd";
            this.acaAecProjectBaseMgd.UseVisualStyleBackColor = true;
            // 
            // acaAecBaseMgd
            // 
            this.acaAecBaseMgd.AutoSize = true;
            this.acaAecBaseMgd.Checked = true;
            this.acaAecBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.acaAecBaseMgd.Location = new System.Drawing.Point(27, 107);
            this.acaAecBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.acaAecBaseMgd.Name = "acaAecBaseMgd";
            this.acaAecBaseMgd.Size = new System.Drawing.Size(109, 19);
            this.acaAecBaseMgd.TabIndex = 2;
            this.acaAecBaseMgd.Text = "AecBaseMgd";
            this.acaAecBaseMgd.UseVisualStyleBackColor = true;
            // 
            // tpAME
            // 
            this.tpAME.Controls.Add(this.checkBox9);
            this.tpAME.Controls.Add(this.checkBox11);
            this.tpAME.Controls.Add(this.checkBox12);
            this.tpAME.Controls.Add(this.ameAecStructureMgd);
            this.tpAME.Controls.Add(this.ameAecPropDataMgd);
            this.tpAME.Controls.Add(this.ameAecRcpMgd);
            this.tpAME.Controls.Add(this.ameAecUIBaseMgd);
            this.tpAME.Controls.Add(this.ameAecUtilityMgd);
            this.tpAME.Controls.Add(this.ameAecArchMgd);
            this.tpAME.Controls.Add(this.ameAecArchDACHMgd);
            this.tpAME.Controls.Add(this.ameAecBaseUtilsMgd);
            this.tpAME.Controls.Add(this.ameAecProjectBaseMgd);
            this.tpAME.Controls.Add(this.ameAecBaseMgd);
            this.tpAME.Controls.Add(this.ameAecbBldSrvMgd);
            this.tpAME.Controls.Add(this.ameAecbElecBaseMgd);
            this.tpAME.Controls.Add(this.ameAecbHvacBaseMgd);
            this.tpAME.Controls.Add(this.ameAecbPartBaseMgd);
            this.tpAME.Controls.Add(this.ameAecbPipeBaseMgd);
            this.tpAME.Controls.Add(this.ameAecbPlumbingBaseMgd);
            this.tpAME.Location = new System.Drawing.Point(4, 25);
            this.tpAME.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpAME.Name = "tpAME";
            this.tpAME.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tpAME.Size = new System.Drawing.Size(536, 279);
            this.tpAME.TabIndex = 4;
            this.tpAME.Text = "AME";
            this.tpAME.UseVisualStyleBackColor = true;
            // 
            // checkBox9
            // 
            this.checkBox9.AutoSize = true;
            this.checkBox9.Checked = true;
            this.checkBox9.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox9.Enabled = false;
            this.checkBox9.Location = new System.Drawing.Point(243, 19);
            this.checkBox9.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox9.Name = "checkBox9";
            this.checkBox9.Size = new System.Drawing.Size(101, 19);
            this.checkBox9.TabIndex = 42;
            this.checkBox9.Text = "AcCoreMgd";
            this.checkBox9.UseVisualStyleBackColor = true;
            // 
            // checkBox11
            // 
            this.checkBox11.AutoSize = true;
            this.checkBox11.Checked = true;
            this.checkBox11.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox11.Enabled = false;
            this.checkBox11.Location = new System.Drawing.Point(148, 19);
            this.checkBox11.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox11.Name = "checkBox11";
            this.checkBox11.Size = new System.Drawing.Size(69, 19);
            this.checkBox11.TabIndex = 41;
            this.checkBox11.Text = "AcMgd";
            this.checkBox11.UseVisualStyleBackColor = true;
            // 
            // checkBox12
            // 
            this.checkBox12.AutoSize = true;
            this.checkBox12.Checked = true;
            this.checkBox12.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox12.Enabled = false;
            this.checkBox12.Location = new System.Drawing.Point(29, 19);
            this.checkBox12.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.checkBox12.Name = "checkBox12";
            this.checkBox12.Size = new System.Drawing.Size(85, 19);
            this.checkBox12.TabIndex = 40;
            this.checkBox12.Text = "AcDbMgd";
            this.checkBox12.UseVisualStyleBackColor = true;
            // 
            // ameAecStructureMgd
            // 
            this.ameAecStructureMgd.AutoSize = true;
            this.ameAecStructureMgd.Checked = true;
            this.ameAecStructureMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecStructureMgd.Location = new System.Drawing.Point(243, 106);
            this.ameAecStructureMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecStructureMgd.Name = "ameAecStructureMgd";
            this.ameAecStructureMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecStructureMgd.TabIndex = 39;
            this.ameAecStructureMgd.Text = "AecStructureMgd";
            this.ameAecStructureMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecPropDataMgd
            // 
            this.ameAecPropDataMgd.AutoSize = true;
            this.ameAecPropDataMgd.Checked = true;
            this.ameAecPropDataMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecPropDataMgd.Location = new System.Drawing.Point(243, 55);
            this.ameAecPropDataMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecPropDataMgd.Name = "ameAecPropDataMgd";
            this.ameAecPropDataMgd.Size = new System.Drawing.Size(141, 19);
            this.ameAecPropDataMgd.TabIndex = 38;
            this.ameAecPropDataMgd.Text = "AecPropDataMgd";
            this.ameAecPropDataMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecRcpMgd
            // 
            this.ameAecRcpMgd.AutoSize = true;
            this.ameAecRcpMgd.Checked = true;
            this.ameAecRcpMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecRcpMgd.Location = new System.Drawing.Point(243, 81);
            this.ameAecRcpMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecRcpMgd.Name = "ameAecRcpMgd";
            this.ameAecRcpMgd.Size = new System.Drawing.Size(101, 19);
            this.ameAecRcpMgd.TabIndex = 37;
            this.ameAecRcpMgd.Text = "AecRcpMgd";
            this.ameAecRcpMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecUIBaseMgd
            // 
            this.ameAecUIBaseMgd.AutoSize = true;
            this.ameAecUIBaseMgd.Checked = true;
            this.ameAecUIBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecUIBaseMgd.Location = new System.Drawing.Point(243, 131);
            this.ameAecUIBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecUIBaseMgd.Name = "ameAecUIBaseMgd";
            this.ameAecUIBaseMgd.Size = new System.Drawing.Size(125, 19);
            this.ameAecUIBaseMgd.TabIndex = 36;
            this.ameAecUIBaseMgd.Text = "AecUIBaseMgd";
            this.ameAecUIBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecUtilityMgd
            // 
            this.ameAecUtilityMgd.AutoSize = true;
            this.ameAecUtilityMgd.Checked = true;
            this.ameAecUtilityMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecUtilityMgd.Location = new System.Drawing.Point(243, 157);
            this.ameAecUtilityMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecUtilityMgd.Name = "ameAecUtilityMgd";
            this.ameAecUtilityMgd.Size = new System.Drawing.Size(133, 19);
            this.ameAecUtilityMgd.TabIndex = 35;
            this.ameAecUtilityMgd.Text = "AecUtilityMgd";
            this.ameAecUtilityMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecArchMgd
            // 
            this.ameAecArchMgd.AutoSize = true;
            this.ameAecArchMgd.Checked = true;
            this.ameAecArchMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecArchMgd.Location = new System.Drawing.Point(29, 55);
            this.ameAecArchMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecArchMgd.Name = "ameAecArchMgd";
            this.ameAecArchMgd.Size = new System.Drawing.Size(109, 19);
            this.ameAecArchMgd.TabIndex = 34;
            this.ameAecArchMgd.Text = "AecArchMgd";
            this.ameAecArchMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecArchDACHMgd
            // 
            this.ameAecArchDACHMgd.AutoSize = true;
            this.ameAecArchDACHMgd.Checked = true;
            this.ameAecArchDACHMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecArchDACHMgd.Location = new System.Drawing.Point(29, 81);
            this.ameAecArchDACHMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecArchDACHMgd.Name = "ameAecArchDACHMgd";
            this.ameAecArchDACHMgd.Size = new System.Drawing.Size(141, 19);
            this.ameAecArchDACHMgd.TabIndex = 33;
            this.ameAecArchDACHMgd.Text = "AecArchDACHMgd";
            this.ameAecArchDACHMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecBaseUtilsMgd
            // 
            this.ameAecBaseUtilsMgd.AutoSize = true;
            this.ameAecBaseUtilsMgd.Checked = true;
            this.ameAecBaseUtilsMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecBaseUtilsMgd.Location = new System.Drawing.Point(29, 131);
            this.ameAecBaseUtilsMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecBaseUtilsMgd.Name = "ameAecBaseUtilsMgd";
            this.ameAecBaseUtilsMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecBaseUtilsMgd.TabIndex = 32;
            this.ameAecBaseUtilsMgd.Text = "AecBaseUtilsMgd";
            this.ameAecBaseUtilsMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecProjectBaseMgd
            // 
            this.ameAecProjectBaseMgd.AutoSize = true;
            this.ameAecProjectBaseMgd.Checked = true;
            this.ameAecProjectBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecProjectBaseMgd.Location = new System.Drawing.Point(29, 157);
            this.ameAecProjectBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecProjectBaseMgd.Name = "ameAecProjectBaseMgd";
            this.ameAecProjectBaseMgd.Size = new System.Drawing.Size(165, 19);
            this.ameAecProjectBaseMgd.TabIndex = 31;
            this.ameAecProjectBaseMgd.Text = "AecProjectBaseMgd";
            this.ameAecProjectBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecBaseMgd
            // 
            this.ameAecBaseMgd.AutoSize = true;
            this.ameAecBaseMgd.Checked = true;
            this.ameAecBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecBaseMgd.Location = new System.Drawing.Point(29, 106);
            this.ameAecBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecBaseMgd.Name = "ameAecBaseMgd";
            this.ameAecBaseMgd.Size = new System.Drawing.Size(109, 19);
            this.ameAecBaseMgd.TabIndex = 30;
            this.ameAecBaseMgd.Text = "AecBaseMgd";
            this.ameAecBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbBldSrvMgd
            // 
            this.ameAecbBldSrvMgd.AutoSize = true;
            this.ameAecbBldSrvMgd.Checked = true;
            this.ameAecbBldSrvMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbBldSrvMgd.Location = new System.Drawing.Point(29, 193);
            this.ameAecbBldSrvMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbBldSrvMgd.Name = "ameAecbBldSrvMgd";
            this.ameAecbBldSrvMgd.Size = new System.Drawing.Size(133, 19);
            this.ameAecbBldSrvMgd.TabIndex = 28;
            this.ameAecbBldSrvMgd.Text = "AecbBldSrvMgd";
            this.ameAecbBldSrvMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbElecBaseMgd
            // 
            this.ameAecbElecBaseMgd.AutoSize = true;
            this.ameAecbElecBaseMgd.Checked = true;
            this.ameAecbElecBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbElecBaseMgd.Location = new System.Drawing.Point(29, 217);
            this.ameAecbElecBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbElecBaseMgd.Name = "ameAecbElecBaseMgd";
            this.ameAecbElecBaseMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecbElecBaseMgd.TabIndex = 27;
            this.ameAecbElecBaseMgd.Text = "AecbElecBaseMgd";
            this.ameAecbElecBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbHvacBaseMgd
            // 
            this.ameAecbHvacBaseMgd.AutoSize = true;
            this.ameAecbHvacBaseMgd.Checked = true;
            this.ameAecbHvacBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbHvacBaseMgd.Location = new System.Drawing.Point(29, 242);
            this.ameAecbHvacBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbHvacBaseMgd.Name = "ameAecbHvacBaseMgd";
            this.ameAecbHvacBaseMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecbHvacBaseMgd.TabIndex = 26;
            this.ameAecbHvacBaseMgd.Text = "AecbHvacBaseMgd";
            this.ameAecbHvacBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbPartBaseMgd
            // 
            this.ameAecbPartBaseMgd.AutoSize = true;
            this.ameAecbPartBaseMgd.Checked = true;
            this.ameAecbPartBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbPartBaseMgd.Location = new System.Drawing.Point(243, 242);
            this.ameAecbPartBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbPartBaseMgd.Name = "ameAecbPartBaseMgd";
            this.ameAecbPartBaseMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecbPartBaseMgd.TabIndex = 25;
            this.ameAecbPartBaseMgd.Text = "AecbPartBaseMgd";
            this.ameAecbPartBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbPipeBaseMgd
            // 
            this.ameAecbPipeBaseMgd.AutoSize = true;
            this.ameAecbPipeBaseMgd.Checked = true;
            this.ameAecbPipeBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbPipeBaseMgd.Location = new System.Drawing.Point(243, 217);
            this.ameAecbPipeBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbPipeBaseMgd.Name = "ameAecbPipeBaseMgd";
            this.ameAecbPipeBaseMgd.Size = new System.Drawing.Size(149, 19);
            this.ameAecbPipeBaseMgd.TabIndex = 24;
            this.ameAecbPipeBaseMgd.Text = "AecbPipeBaseMgd";
            this.ameAecbPipeBaseMgd.UseVisualStyleBackColor = true;
            // 
            // ameAecbPlumbingBaseMgd
            // 
            this.ameAecbPlumbingBaseMgd.AutoSize = true;
            this.ameAecbPlumbingBaseMgd.Checked = true;
            this.ameAecbPlumbingBaseMgd.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ameAecbPlumbingBaseMgd.Location = new System.Drawing.Point(243, 193);
            this.ameAecbPlumbingBaseMgd.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ameAecbPlumbingBaseMgd.Name = "ameAecbPlumbingBaseMgd";
            this.ameAecbPlumbingBaseMgd.Size = new System.Drawing.Size(181, 19);
            this.ameAecbPlumbingBaseMgd.TabIndex = 23;
            this.ameAecbPlumbingBaseMgd.Text = "AecbPlumbingBaseMgd";
            this.ameAecbPlumbingBaseMgd.UseVisualStyleBackColor = true;
            // 
            // btnClearAll
            // 
            this.btnClearAll.Location = new System.Drawing.Point(339, 461);
            this.btnClearAll.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnClearAll.Name = "btnClearAll";
            this.btnClearAll.Size = new System.Drawing.Size(100, 26);
            this.btnClearAll.TabIndex = 26;
            this.btnClearAll.Text = "Clear All";
            this.btnClearAll.UseVisualStyleBackColor = true;
            this.btnClearAll.Click += new System.EventHandler(this.btnClearAll_Click);
            // 
            // btnSelectAll
            // 
            this.btnSelectAll.Location = new System.Drawing.Point(123, 461);
            this.btnSelectAll.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnSelectAll.Name = "btnSelectAll";
            this.btnSelectAll.Size = new System.Drawing.Size(100, 26);
            this.btnSelectAll.TabIndex = 25;
            this.btnSelectAll.Text = "Select All";
            this.btnSelectAll.UseVisualStyleBackColor = true;
            this.btnSelectAll.Click += new System.EventHandler(this.btnSelectAll_Click);
            // 
            // lblRunAs
            // 
            this.lblRunAs.AutoSize = true;
            this.lblRunAs.Location = new System.Drawing.Point(413, 114);
            this.lblRunAs.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblRunAs.Name = "lblRunAs";
            this.lblRunAs.Size = new System.Drawing.Size(63, 15);
            this.lblRunAs.TabIndex = 27;
            this.lblRunAs.Text = "Run As:";
            // 
            // cbRunAs
            // 
            this.cbRunAs.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbRunAs.FormattingEnabled = true;
            this.cbRunAs.Location = new System.Drawing.Point(477, 111);
            this.cbRunAs.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cbRunAs.Name = "cbRunAs";
            this.cbRunAs.Size = new System.Drawing.Size(75, 23);
            this.cbRunAs.TabIndex = 28;
            this.cbRunAs.SelectedIndexChanged += new System.EventHandler(this.cbRunAs_SelectedIndexChanged);
            // 
            // ObjectARXLocatorForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(569, 554);
            this.Controls.Add(this.cbRunAs);
            this.Controls.Add(this.lblRunAs);
            this.Controls.Add(this.btnClearAll);
            this.Controls.Add(this.tabControlRefs);
            this.Controls.Add(this.btnSelectAll);
            this.Controls.Add(this.searchacad);
            this.Controls.Add(this.acadpath);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.aboutbox);
            this.Controls.Add(this.searchsdk);
            this.Controls.Add(this.sdkpath);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "ObjectARXLocatorForm";
            this.Text = "AutoCAD .NET Wizard Configurator";
            this.Load += new System.EventHandler(this.ObjectARXLocatorForm_Load);
            this.tabControlRefs.ResumeLayout(false);
            this.tpAutoCAD.ResumeLayout(false);
            this.tpAutoCAD.PerformLayout();
            this.tpMap3D.ResumeLayout(false);
            this.tpMap3D.PerformLayout();
            this.tpCivil3D.ResumeLayout(false);
            this.tpCivil3D.PerformLayout();
            this.tpACA.ResumeLayout(false);
            this.tpACA.PerformLayout();
            this.tpAME.ResumeLayout(false);
            this.tpAME.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button searchsdk;
        public System.Windows.Forms.TextBox sdkpath;
        private System.Windows.Forms.Button aboutbox;
        private System.Windows.Forms.Button searchacad;
        public System.Windows.Forms.TextBox acadpath;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TabControl tabControlRefs;
        private System.Windows.Forms.TabPage tpAutoCAD;
        public System.Windows.Forms.CheckBox accoremgd;
        public System.Windows.Forms.CheckBox accui;
        public System.Windows.Forms.CheckBox acdbmgdbrep;
        public System.Windows.Forms.CheckBox interop1;
        public System.Windows.Forms.CheckBox interop0;
        public System.Windows.Forms.CheckBox acdx;
        public System.Windows.Forms.CheckBox actcmgd;
        public System.Windows.Forms.CheckBox acwindows;
        public System.Windows.Forms.CheckBox adwindows;
        public System.Windows.Forms.CheckBox acmgd;
        public System.Windows.Forms.CheckBox acdbmgd;
        private System.Windows.Forms.TabPage tpMap3D;
        private System.Windows.Forms.TabPage tpCivil3D;
        public System.Windows.Forms.CheckBox AcMPloygonMgd;
        public System.Windows.Forms.CheckBox OsgeoFdoGeom;
        public System.Windows.Forms.CheckBox OsgeoFdoCommon;
        public System.Windows.Forms.CheckBox OsgeoFdo;
        public System.Windows.Forms.CheckBox OsgeoMgPlatformBase;
        public System.Windows.Forms.CheckBox OsgeoMgGeom;
        public System.Windows.Forms.CheckBox OsgeoMgFoundation;
        public System.Windows.Forms.CheckBox MgdMapApi;
        public System.Windows.Forms.CheckBox mapPlatformCore;
        public System.Windows.Forms.CheckBox mapPlatform;
        public System.Windows.Forms.CheckBox aecBaseObjectLib;
        public System.Windows.Forms.CheckBox aecBaseAppLip;
        public System.Windows.Forms.CheckBox autocadTypeLib;
        public System.Windows.Forms.CheckBox aeccSurvey;
        public System.Windows.Forms.CheckBox aeccPipe;
        public System.Windows.Forms.CheckBox aeccLand;
        public System.Windows.Forms.CheckBox aeccRoadway;
        public System.Windows.Forms.CheckBox aecBaseMgd;
        public System.Windows.Forms.CheckBox dbxCommon;
        public System.Windows.Forms.CheckBox aeccDbMgd;
        private System.Windows.Forms.TabPage tpACA;
        private System.Windows.Forms.TabPage tpAME;
        public System.Windows.Forms.CheckBox acaAecArchMgd;
        public System.Windows.Forms.CheckBox acaArchDACHMgd;
        public System.Windows.Forms.CheckBox acaAecBaseUtilsMgd;
        public System.Windows.Forms.CheckBox acaAecProjectBaseMgd;
        public System.Windows.Forms.CheckBox acaAecBaseMgd;
        public System.Windows.Forms.CheckBox acaAecPropDataMgd;
        public System.Windows.Forms.CheckBox acaAecRcpMgd;
        public System.Windows.Forms.CheckBox acaAecUIBaseMgd;
        public System.Windows.Forms.CheckBox acaAecUtilityMgd;
        public System.Windows.Forms.CheckBox ameAecbBldSrvMgd;
        public System.Windows.Forms.CheckBox ameAecbElecBaseMgd;
        public System.Windows.Forms.CheckBox ameAecbHvacBaseMgd;
        public System.Windows.Forms.CheckBox ameAecbPartBaseMgd;
        public System.Windows.Forms.CheckBox ameAecbPipeBaseMgd;
        public System.Windows.Forms.CheckBox ameAecbPlumbingBaseMgd;
        private System.Windows.Forms.Button btnClearAll;
        private System.Windows.Forms.Button btnSelectAll;
        public System.Windows.Forms.CheckBox acaAecStructureMgd;
        public System.Windows.Forms.CheckBox ameAecStructureMgd;
        public System.Windows.Forms.CheckBox ameAecPropDataMgd;
        public System.Windows.Forms.CheckBox ameAecRcpMgd;
        public System.Windows.Forms.CheckBox ameAecUIBaseMgd;
        public System.Windows.Forms.CheckBox ameAecUtilityMgd;
        public System.Windows.Forms.CheckBox ameAecArchMgd;
        public System.Windows.Forms.CheckBox ameAecArchDACHMgd;
        public System.Windows.Forms.CheckBox ameAecBaseUtilsMgd;
        public System.Windows.Forms.CheckBox ameAecProjectBaseMgd;
        public System.Windows.Forms.CheckBox ameAecBaseMgd;
        public System.Windows.Forms.CheckBox checkBox3;
        public System.Windows.Forms.CheckBox checkBox2;
        public System.Windows.Forms.CheckBox checkBox1;
        public System.Windows.Forms.CheckBox checkBox9;
        public System.Windows.Forms.CheckBox checkBox11;
        public System.Windows.Forms.CheckBox checkBox12;
        private System.Windows.Forms.Label lblRunAs;
        private System.Windows.Forms.ComboBox cbRunAs;
        public System.Windows.Forms.CheckBox checkBox4;
        public System.Windows.Forms.CheckBox checkBox5;
        public System.Windows.Forms.CheckBox checkBox6;
        public System.Windows.Forms.CheckBox checkBox7;
        public System.Windows.Forms.CheckBox checkBox8;
        public System.Windows.Forms.CheckBox checkBox10;
    }
}